<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Unit Outline COS10026 Web Technology Project">
    <meta name="keywords" content="recycling, Swinburne, project, Technology, reusing, renewable, renew, e-waste, sustainability, environment">
    <meta name="author" content="Karim, Ishmam, Maria, Moniratanak">
    <title>RENEW</title>
    <link rel="stylesheet" href="<?php echo $css_file?>">
    
</head>
<body>

<header>
    <img src="images/company-logo.png" alt="company-logo" class="logo">
    <h1>RENEW</h1>
    <p>Building a cleaner future through renewable energy innovation.</p>